<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.luoyi</groupId>
        <artifactId>luoyi</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>luoyi-example</artifactId>
    <packaging>pom</packaging>

    <description>
        该包是测试组件，每个子包，代表一个组件。
    </description>
    <url>https://github.com/iqeq00/luoyi</url>

    <modules>
        <module>luoyi-example-jd</module>
        <module>luoyi-example-rocketmq</module>
        <module>luoyi-example-yihu</module>
        <module>luoyi-example-mybatis</module>
    </modules>

</project>