package com.luoyi.example.yihu.jwt;

import cn.hutool.core.date.DateUtil;
import cn.hutool.core.date.LocalDateTimeUtil;
import cn.hutool.jwt.JWT;
import cn.hutool.jwt.JWTUtil;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jws;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;

import java.time.LocalDateTime;
import java.util.Date;
import java.util.Map;

public class JwtCase {

    public static void main(String[] args) {

        String jwt = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImNlcnQtYnVpbHQtaW4iLCJ0eXAiOiJKV1QifQ.eyJvd25lciI6ImxhcGxhY2VsYWIiLCJuYW1lIjoidGVzdDIwMjUiLCJjcmVhdGVkVGltZSI6IjIwMjUtMDEtMDdUMTA6MzQ6NTFaIiwidXBkYXRlZFRpbWUiOiIiLCJpZCI6ImRiZmMzM2NmLTc1MmQtNGY3Mi04MzIwLTA1ZjBkZTUyYmQ0NyIsInR5cGUiOiJub3JtYWwtdXNlciIsInBhc3N3b3JkIjoiIiwicGFzc3dvcmRTYWx0IjoiIiwicGFzc3dvcmRUeXBlIjoic2FsdCIsImRpc3BsYXlOYW1lIjoidGVzdDIwMjUiLCJmaXJzdE5hbWUiOiIiLCJsYXN0TmFtZSI6IiIsImF2YXRhciI6IiIsImF2YXRhclR5cGUiOiIiLCJwZXJtYW5lbnRBdmF0YXIiOiIiLCJlbWFpbCI6InRlc3RAYWkuY29tIiwiZW1haWxWZXJpZmllZCI6ZmFsc2UsInBob25lIjoiIiwiY291bnRyeUNvZGUiOiJDTiIsInJlZ2lvbiI6IiIsImxvY2F0aW9uIjoiIiwiYWRkcmVzcyI6W10sImFmZmlsaWF0aW9uIjoibGFwbGFjZWxhYiIsInRpdGxlIjoiIiwiaWRDYXJkVHlwZSI6IiIsImlkQ2FyZCI6IiIsImhvbWVwYWdlIjoiIiwiYmlvIjoiIiwibGFuZ3VhZ2UiOiIiLCJnZW5kZXIiOiIiLCJiaXJ0aGRheSI6IiIsImVkdWNhdGlvbiI6IiIsInNjb3JlIjoyMDAwLCJrYXJtYSI6MCwicmFua2luZyI6MTQ3LCJpc0RlZmF1bHRBdmF0YXIiOmZhbHNlLCJpc09ubGluZSI6ZmFsc2UsImlzQWRtaW4iOmZhbHNlLCJpc0ZvcmJpZGRlbiI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInNpZ251cEFwcGxpY2F0aW9uIjoibGFwbGFjZWxhYl9haV9pbnQiLCJoYXNoIjoiIiwicHJlSGFzaCI6IiIsImFjY2Vzc0tleSI6IiIsImFjY2Vzc1NlY3JldCI6IiIsImdpdGh1YiI6IiIsImdvb2dsZSI6IiIsInFxIjoiIiwid2VjaGF0IjoiIiwiZmFjZWJvb2siOiIiLCJkaW5ndGFsayI6IiIsIndlaWJvIjoiIiwiZ2l0ZWUiOiIiLCJsaW5rZWRpbiI6IiIsIndlY29tIjoiIiwibGFyayI6IiIsImdpdGxhYiI6IiIsImNyZWF0ZWRJcCI6IiIsImxhc3RTaWduaW5UaW1lIjoiIiwibGFzdFNpZ25pbklwIjoiIiwicHJlZmVycmVkTWZhVHlwZSI6IiIsInJlY292ZXJ5Q29kZXMiOm51bGwsInRvdHBTZWNyZXQiOiIiLCJtZmFQaG9uZUVuYWJsZWQiOmZhbHNlLCJtZmFFbWFpbEVuYWJsZWQiOmZhbHNlLCJsZGFwIjoiIiwicHJvcGVydGllcyI6e30sInJvbGVzIjpbXSwicGVybWlzc2lvbnMiOltdLCJncm91cHMiOltdLCJsYXN0U2lnbmluV3JvbmdUaW1lIjoiIiwic2lnbmluV3JvbmdUaW1lcyI6MCwidG9rZW5UeXBlIjoiYWNjZXNzLXRva2VuIiwidGFnIjoiIiwic2NvcGUiOiJyZWFkIiwiaXNzIjoiaHR0cHM6Ly9pbnQtYXV0aC1hZG1pbi5sYXBsYWNlbGFiLmFpIiwic3ViIjoiZGJmYzMzY2YtNzUyZC00ZjcyLTgzMjAtMDVmMGRlNTJiZDQ3IiwiYXVkIjpbIjg1YWU1NWFiYWI4NTg3NzMzZDY3Il0sImV4cCI6MTczODc2ODU5NiwibmJmIjoxNzM4MTYzNzk2LCJpYXQiOjE3MzgxNjM3OTYsImp0aSI6ImFkbWluLzE0MDZlYjlmLTg3M2MtNDMzMi1hNzU4LTdiOWI3NDgzYTQwMyJ9.x4CkPN8XH67R65yUMVPw3Vo0HnA63pYujR1mn5wkhJNBTuh3uRILzx3h3Zs5RyaidYMVd_obIRWilyp7Dj6cOSY3vo3dl4zjDhZMiBOpV_XiJxDeUjXaeyJMph2YdnZKJGIy6CERGiPFP7hcqNxGJGhFJt7EFE0BirC7yJ_8ErQdCOK9lrbPm6nHHPxfzQ7dToN2MbOqdpjQ6T9W6GOT93gkVlGI8CO1M2E9jrbHPq-CNioXeqO65o1YixyfKsdOnrRU2FwDKrjfIXu1ZGArNKK88AQjLO5BPjVQ3eTTvGVtxTghWztOxRykL86fyLuFaaQ3KHo6svrU59kztVoYHH1BiYrLWoB_Yo7kJ74WGAkzwHyoe3yB3X7KI6jAh4n7pJ_9SOAAYHMC_R88-rABYCsvWndj3UqbGNBgL2k-owXJVlY-In0zHsWOeowEZorxytxcbHiIv7Rno7Gz7brm9L26gG90lGFteUQ95JfgnxXUgebdn5DS7arrgD6QPG0OFSIkywq_wwpazIRYUceaqyIT34FhrtXFRTxDil5VphfETLvdpXxKomCuF3TvgyAdCndpe_t3iCvOuRgsn3dYAWgFtrEAMwHEuAJnwE6HKQ0M7w_5kcB5sXWpLFVQSokiQNYMV4hy14qfdgk5RkwWNTiTcY-fXw28fqkQiyYmT5M";

        JWT jwtObject = JWTUtil.parseToken(jwt);
// 获取 Header 和 Payload
        System.out.println("Header: " + jwtObject.getHeader());
        System.out.println("Payload: " + jwtObject.getPayload());
        System.out.println("exp: " + jwtObject.getPayloads().getLong("exp"));

        Long exp = jwtObject.getPayloads().getLong("exp");
        // 转换为 LocalDateTime
        LocalDateTime dateTime = LocalDateTimeUtil.of(exp*1000);

        // 输出结果
        System.out.println("转换后的 LocalDateTime: " + dateTime);
    }
}
